import React from 'react';

function VoiceAssistant() {
  return (
    <>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus dolores officia molestias pariatur quae accusantium porro! Nihil quas animi eligendi iusto officia delectus a quisquam sapiente modi non vero suscipit voluptatum autem consequatur sunt doloremque vel, rem hic necessitatibus quae aspernatur et! A perspiciatis iure possimus maiores dignissimos dolor corrupti et temporibus veniam quos nostrum aperiam quibusdam molestias, optio ipsum adipisci voluptate ratione explicabo odio at quo maxime fugiat. Eveniet ex amet neque. Magnam exercitationem atque perferendis molestias, omnis possimus hic officiis adipisci mollitia cum repellendus aliquid harum amet, commodi qui, dicta sequi animi quidem voluptates blanditiis fugiat. Modi, dolor quo necessitatibus esse ea officia a minus similique, tempora praesentium accusantium aperiam beatae quia aspernatur delectus voluptatum odit eligendi dolores. Quibusdam reiciendis architecto blanditiis. Officiis laudantium nobis distinctio aspernatur aperiam minima ut corporis cum totam beatae iusto minus corrupti, dignissimos, necessitatibus, assumenda ad ipsum quasi sed molestiae voluptatibus magni a. Aliquid amet eius voluptatibus nam doloremque non unde rem? Distinctio quibusdam optio sed explicabo obcaecati quos, eius eos ea facere eveniet atque debitis minus eaque tenetur esse id nihil. Culpa incidunt rerum doloribus accusantium facere sit voluptatem consectetur esse! Quos quod accusantium obcaecati, perspiciatis blanditiis quidem, nobis nihil error, ea quas odio aspernatur quam cupiditate? Ratione, saepe fuga accusantium est omnis, reprehenderit cupiditate, odit porro maiores nesciunt atque doloribus quia error. Porro nostrum sequi non corrupti molestias. Incidunt autem iste adipisci suscipit facere sed doloremque cumque in excepturi molestiae beatae consectetur corporis repellat, eligendi nulla eaque commodi error quia voluptates aperiam voluptas. Esse repellendus adipisci, voluptas in corporis asperiores reiciendis iste a atque, cum illo magnam. Reprehenderit aut dolorum dolores quisquam libero explicabo sit maxime, iste assumenda, recusandae quaerat nihil delectus provident soluta nesciunt, debitis ut. Iure qui, deserunt saepe ut, minima assumenda quidem cupiditate alias repellat suscipit dolore odio.</h1>
    </>
  );
}

export default VoiceAssistant;
